### ISSUE TITLE
why seconds?

### ISSUE THREAD

**Issue by gstvrmrlpz** [JJ/2016-ea-languages-wcci#10]
It is a unit too big for fast versions...

**Comment by JJ** [comment]
milliseconds maybe?

**Comment by mariosky** [comment]
milliseconds with nanosecond detail

**Comment by gstvrmrlpz** [comment]
milliseconds with nanosecond detail == nanoseconds

**Comment by mariosky** [comment]
sorry, precision is the word I was looking for.
like 2.123456789 seconds :)

**Comment by JJ** [comment]
We left seconds. Can change it in the next version.
