### ISSUE TITLE
Add Clojure & Common Lisp

### ISSUE THREAD

**Issue by mariosky** [JJ/2016-ea-languages-wcci#15]
@JJ  please run these two last scripts and update the CSVs so I can write the showdown results.

**Comment by JJ** [comment]
How do I install Common Lisp?

2016-01-27 8:01 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> Assigned #15 https://github.com/JJ/2016-ea-languages-wcci/issues/15 to
> @JJ https://github.com/JJ.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/2016-ea-languages-wcci/issues/15#event-527652287.

## 

JJ

**Comment by mariosky** [comment]
From the readme:
Download SBCL (binaries) from http://www.sbcl.org
Maybe:  apt-get install sbcl

**Comment by JJ** [comment]
bitflip.clj does not work. I'm using clojure from the repos, 1.4. Should I
use 1.8 or other version?

2016-01-27 8:07 GMT+01:00 Mario Garcia Valdez notifications@github.com:

> From the readme:
> Download SBCL (binaries) from http://www.sbcl.org
> Maybe: apt-get install sbcl
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/2016-ea-languages-wcci/issues/15#issuecomment-175455173
> .

## 

JJ

**Comment by mariosky** [comment]
1.8 please

**Comment by JJ** [comment]
Definitely not working. Using 1.8 REPL and it just gets stuck, doing nothing.
