### ISSUE TITLE
Please JJ, give us a little more info

### ISSUE THREAD

**Issue by vrivas** [JJ/2016-ea-languages-wcci#3]
Hi JJ,
Please, give us a some information about the state and aim of this paper. 
Is it a new version of a previous paper, so that text has to be deeply changed?
Is it necessary to make new experiments or analyse the results?
According to the name, I imagine this is for http://wcci2016.org/, is it for any special session?
The deadline is 15/Jan/2016, isn't it?
Thanks!!

**Comment by dcamacho** [comment]
Hi,

I just download and compile the paper, I think a couple of .bib files are missing (geneura, GA-general). The paper is currently quite complete (14-15 pages) and it looks to be close to be finish, so what kind of contribution could be expected? it is possible to include something new? e.g. related to state-of-the-art? other analysis?. 

I just read the paper and I think the experimental phase is really complete, maybe it will be quite difficult (for future readers) easily distinguish so many coloured lines , maybe it could interesting to divide the current plots into smaller ones dividing the comparison amongst languages based on the data structures used (String, Bit Vector).

bye, david

**Comment by JJ** [comment]
More benchmarks (binary decoding to floating point) more languages (c# for
instance) and maybe more data structures. Also improving existing
implementations and a reproductible benchmark via Docker and @iblancasa

**Comment by JJ** [comment]
2015-11-24 13:55 GMT+01:00 JJ Merelo jjmerelo@gmail.com:

> More benchmarks (binary decoding to floating point) more languages (c# for
> instance) and maybe more data structures. Also improving existing
> implementations and a reproductible benchmark via Docker and @iblancasa
> 
> More analysis, too, and possible generalizations.  Can you help with
> putting it in CEC format? I asked @fergunet, but didn't do it.

**Comment by dcamacho** [comment]
sure...
