### ISSUE TITLE
Uniform and improve benchmarks

### ISSUE THREAD

**Issue by JJ** [JJ/2016-ea-languages-wcci#7]
For instance, Pepe Gallardo mentioned in Twitter that the Scala maxones could e much faster. Check for differences that could influence the result, test different data structures, improve speed where it can be improved.

**Comment by gstvrmrlpz** [comment]
why in csharp xover not every bit can be swapped?
all implementations must be the same...

**Comment by mariosky** [comment]
Hi, At first It was implemented for all bits with a flip coin for each, as
in C, but then I saw that all others were using a random point and starting
from flip all remaining bits or even choosing two points and only flipping
the bits between them.

I ask about it, but it seems that there is not an implementation guide yet.

I agree that this guide should be implemented. As some were noticing there
are other issues like the need to have the resulting chromosome as a new
array, not changing the bits in place.

I can start by doing a survey about every implementation and noticing those
changes.
 But I think that a developer could opt for a faster implementation in his
language even if it not complies with certain rules.

**Comment by mariosky** [comment]
I will modify the C# version to a 1 point crossover resulting in 2 new
arrays.

**Comment by JJ** [comment]
Two point crossover is the way it's done...

**Comment by mariosky** [comment]
Ok Two
