### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by JJ** [JJ/2016-ea-languages-wcci#9]
Propose and think about a new title here or changing the paper itself.

**Comment by vrivas** [comment]
Current title: Benchmarking languages for evolutionary algorithms
Proposals: 
- The effect of programming languages in evolutionary algorithms' performance

**Comment by pacastillo** [comment]
Other proposal:

 How different programming languages affect the performance in evolutionary algorithm experiments

**Comment by mariosky** [comment]
Important aspects about the paper that maybe should be on the title:
Is not rigorous or conclusive.
Performance is not the only thing, we can also compare and learn about the
paradigms and styles of modern languages is somewhat didactic.
This could be something that is alive and also evolving, a repository of
best practices , A student was joking How about an implementation in the
 whitespace or LOLCODE languages i didnt know about those :)

**Comment by JJ** [comment]
It's a lot of stuff for a title... Maybe for the abstract?
